# BikeSQL checker

In [2]:
import os
import sys
import pandas as pd
import sqlalchemy as sqla
# add current working directory to sys.path to import config.py
sys.path.append(os.getcwd())
try:
    import config
    print("config checked", flush=True)
except ImportError:
    print("Error: config.py not found,pls make one at first.")
    raise

DB_NAME = getattr(config, "DB_NAME", "COMP30830_SW")

engine = sqla.create_engine(
    f"mysql+pymysql://{config.DB_USER}:{config.DB_PASSWORD}@{config.DB_HOST}/{DB_NAME}"
    f"?charset=utf8mb4"
)

# 小工具：返回 DataFrame
def q(sql, params=None):
    return pd.read_sql(sqla.text(sql), engine, params=params)

config checked

## Base Stats

In [ ]:
# basic stats
display(q("SELECT COUNT(*) AS station_count FROM station"))
display(q("SELECT COUNT(*) AS availability_count FROM availability"))

# reord count by day
display(q("SELECT DATE(last_update) AS day, COUNT(*) AS records FROM availability GROUP BY DATE(last_update) ORDER BY day"))

   station_count
0            115

   availability_count
0               66350

          day  records
0  2026-02-03    17073
1  2026-02-04    32678
2  2026-02-05    16369
3  2026-02-12      230

   records
0    17073

## feature daily info

In [10]:
daily_sql = '''
SELECT
    DATE(last_update) AS day,
    AVG(available_bikes) AS avg_bikes,
    AVG(available_bike_stands) AS avg_stands,
    COUNT(*) AS records
FROM availability
GROUP BY DATE(last_update)
ORDER BY day;
'''

q(daily_sql).head()

          day  avg_bikes  avg_stands  records
0  2026-02-03    11.7856     19.7473    17073
1  2026-02-04    11.5565     20.0536    32678
2  2026-02-05    11.7692     19.8699    16369
3  2026-02-12    12.1870     19.6130      230